# This is the regional configuration file required by the application to specify the VPCs and/or subnets it is supposed to track 
# along with configuration required to setup traffic mirroring in those VPCs and/or subnets . 
# The configuration file follows a naming convention of <REGION_NAME>.yaml e.g. us-east-1.yaml
---
# VPC related configuration. You can enter configuration related to multiple VPCs here
vpcs:
- vpcId: <INSERT_VALUE> # required e.g. vpc-1a2b3c4d
  
  # Use this property to use an existing Traffic Mirror filter based on traffic source instance tag.
  # This solution uses instance tag key value of "server_type" with allowed values of 'web', 'app' and 'db'. 
  # If you prefer to use other values for instance tag key/value, you would need to update this paramter accordingly.
  filterID-web: <INSERT_VALUE> # required e.g. tmf-035ba57dba06a5467
  filterID-app: <INSERT_VALUE> # required e.g. tmf-019e92beff0755e82
  filterID-db:  <INSERT_VALUE> # required e.g. tmf-038f1b7853bf5006f
  
  # Set this property to use an existing Traffic Mirror target for all sessions in a given AZ. If using this option
  # we recommend using a target of type 'network-load-balancer' because a network-load-balancer based target
  # does not have any limits on the number of sources that mirror to it. 
  # Update the parameter based on AZ ID of the target.
  targetID-az1: <INSERT_VALUE> # Use this paramter for target in AZ ID 1, e.g. tmt-0d1eb1fc980833f4e
  targetID-az2: <INSERT_VALUE> # Use this paramter for target in AZ ID 2, e.g. tmt-0102eacfa984f3dc2
  targetID-az3: <INSERT_VALUE> # Use this paramter for target in AZ ID 3, e.g. tmt-055b63b6900cba6ca


# Subnet related configuration. You can enter configuration related to multiple subnets here
# NOTE: A subnet configuration takes priority over VPC configuration
subnets:
- subnetId: <INSERT_VALUE> # required e.g. subnet-ecf5d8b6

  # Use this property to use an existing Traffic Mirror filter based on traffic source instance tag.
  # This solution uses instance tag key value of "server_type" with allowed values of 'web', 'app' and 'db'. 
  # If you prefer to use other values for instance tag key/value, you would need to update this paramter accordingly.
  filterID-web: <INSERT_VALUE> # required e.g. tmf-035ba57dba06a5467
  filterID-app: <INSERT_VALUE> # required e.g. tmf-019e92beff0755e82
  filterID-db:  <INSERT_VALUE> # required e.g. tmf-038f1b7853bf5006f
  
  # Set this property to use an existing Traffic Mirror target for all sessions in a given AZ. If using this option
  # we recommend using a target of type 'network-load-balancer' because a network-load-balancer based target
  # does not have any limits on the number of sources that mirror to it. 
  # Update the parameter based on AZ ID of the target.
  targetID-az1: <INSERT_VALUE> # Use this paramter for target in AZ ID 1, e.g. tmt-0d1eb1fc980833f4e
  targetID-az2: <INSERT_VALUE> # Use this paramter for target in AZ ID 2, e.g. tmt-0102eacfa984f3dc2
  targetID-az3: <INSERT_VALUE> # Use this paramter for target in AZ ID 3, e.g. tmt-055b63b6900cba6ca
  

# Tags related configuration. You can enter configuration related to multiple tags here
# NOTE: A tag configuration takes priority over subnet configuration. Also, this works only for tags created during instance launch
# Any modifications to tags later would not be processed.
tags:
- tagList: # At least one tag (pair of of {key, value}) is required
  - Key: <INSERT_VALUE> # e.g. TagKey
    Value: <INSERT_VALUE> # required e.g. TagValue
  - Key: <INSERT_VALUE>
    Value: <INSERT_VALUE>

  # Use this property to use an existing Traffic Mirror filter based on traffic source instance tag.
  # This solution uses instance tag key value of "server_type" with allowed values of 'web', 'app' and 'db'. 
  # If you prefer to use other values for instance tag key/value, you would need to update this paramter accordingly.
  filterID-web: <INSERT_VALUE> # required e.g. tmf-035ba57dba06a5467
  filterID-app: <INSERT_VALUE> # required e.g. tmf-019e92beff0755e82
  filterID-db:  <INSERT_VALUE> # required e.g. tmf-038f1b7853bf5006f
  
  # Set this property to use an existing Traffic Mirror target for all sessions in a given AZ. If using this option
  # we recommend using a target of type 'network-load-balancer' because a network-load-balancer based target
  # does not have any limits on the number of sources that mirror to it. 
  # Update the parameter based on AZ ID of the target.
  targetID-az1: <INSERT_VALUE> # Use this paramter for target in AZ ID 1, e.g. tmt-0d1eb1fc980833f4e
  targetID-az2: <INSERT_VALUE> # Use this paramter for target in AZ ID 2, e.g. tmt-0102eacfa984f3dc2
  targetID-az3: <INSERT_VALUE> # Use this paramter for target in AZ ID 3, e.g. tmt-055b63b6900cba6ca